---
safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /2.2/
url: http://localhost:4000/

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink:   date
paginate:    6
paginate_files: 
  - news.html
  - index.html